import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/Components/Common/Footer/Footer";
import BackToTop from "@/Components/BackToTop/BackToTop";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Limo Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="container relative mx-auto max-w-[1400px] p-2">
          {/* <ReviewButton/> */}
          <BackToTop />
          {children}
          <ToastContainer />
          <Footer />
        </main>
      </body>
    </html>
  );
}
